{% set name = "decasu" %}
{% set version = "0.7.2" %}
{% set sha256 = "16785fcdcf7a8f5af26262203227982bcc19286587139cd2b0a63e6f01917b72" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - decasu_hpix_mapper.py = decasu.decasu_hpix_mapper:main
    - decasu_tile_mapper.py = decasu.decasu_tile_mapper:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - healpy
    - astropy-base
    - healsparse
    - healsparse
    - fitsio
    - esutil
    - LSSTDESC.Coord
    - pyyaml

test:
  imports:
    - decasu
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/erykoff/decasu
  summary: DECam (and HSC and LSSTCam) Survey Property Maps with HealSparse
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/erykoff/decasu

extra:
  recipe-maintainers:
    - erykoff
